---
- name: Remove snakeoil certificate
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/ssl/private/ssl-cert-snakeoil.key
    - /etc/ssl/certs/ssl-cert-snakeoil.pem
  become: true

- name: Remove popularity-contest
  apt:
    name: popularity-contest
    state: absent
    purge: yes
  become: true

# NOTE: Although the package popularity-contest will be uninstalled,
#       some of these files are still available on systems.
- name: Remove popularity-contest cronjobs
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/cron.d/popularity-contest
    - /etc/cron.daily/popularity-contest
  become: true
