---
- name: Restart rsyslog service
  service:
    name: rsyslog
    state: restarted
  become: true

- name: Forward syslog message to local fluentd daemon
  template:
    src: 70-fluentd.conf.j2
    dest: /etc/rsyslog.d/70-fluentd.conf
    owner: root
    group: root
    mode: 0644
  become: true
  notify: Restart rsyslog service

- name: Remove snakeoil certificate
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/ssl/private/ssl-cert-snakeoil.key
    - /etc/ssl/certs/ssl-cert-snakeoil.pem
  become: true
