# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Restart rsyslog service
  service:
    name: rsyslog
    state: restarted
  become: true

- name: Set ssh authorized keys
  authorized_key:
    key: "{{ item }}"
    user: root
  with_items: "{{ authorized_keys }}"
  become: true

# Install postfix here to be able to disable ipv6 (if required, will normally be installed by osa)
- name: Install postfix
  package:
    name: postfix
    state: present
  when: disable_ipv6|bool
  become: true

# NOTE: Change "dest" to "path" with Ansible >= 2.3
- name: Only use ipv4 for postfix
  lineinfile:
    dest: /etc/postfix/main.cf
    regexp: '^inet_protocols ='
    line: 'inet_protocols = ipv4'
  when: disable_ipv6|bool
  become: true

- name: Generate /etc/hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
  become: true
  tags: hosts

- name: Forward syslog message to local fluentd daemon
  template:
    src: 70-fluentd.conf.j2
    dest: /etc/rsyslog.d/70-fluentd.conf
    owner: root
    group: root
    mode: 0644
  become: true
  notify: Restart rsyslog service
