# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Copy sources.list file
  copy:
    src: sources.list
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644
  become: true

- name: Update package cache
  package:
    update_cache: yes
  become: true

- name: Upgrade all packages
  package:
    upgrade: dist
  become: true

- name: Restart rsyslog service
  service:
    name: rsyslog
    state: restarted
  become: true

- name: Set ssh authorized keys
  authorized_key:
    key: "{{ item }}"
    user: root
  with_items: "{{ authorized_keys }}"
  become: true

- name: Remove snakeoil certificate
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/ssl/private/ssl-cert-snakeoil.key
    - /etc/ssl/certs/ssl-cert-snakeoil.pem
  become: true

# http://truemetal.org/universe/blog/2013/03/disable-ipv6-on-linux-centos/
- name: Disable ipv6 support
  sysctl:
    name: "{{ item }}"
    value: 1
    state: present
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
  when: disable_ipv6|bool
  become: true

# Install postfix here to be able to disable ipv6 (if required, will normally be installed by osa)
- name: Install postfix
  package:
    name: postfix
    state: present
  when: disable_ipv6|bool
  become: true

# NOTE: Change "dest" to "path" with Ansible >= 2.3
- name: Only use ipv4 for postfix
  lineinfile:
    dest: /etc/postfix/main.cf
    regexp: '^inet_protocols ='
    line: 'inet_protocols = ipv4'
  when: disable_ipv6|bool
  become: true

- name: Generate /etc/hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
  become: true
  tags: hosts
