---
- name: Create custom facts directory
  file:
    path: /etc/ansible/facts.d
    state: "directory"
    owner: root
    group: root
    mode: 0755
  become: true

- name: Copy fact files
  copy:
    src: "facts/{{ item }}.fact"
    dest: "/etc/ansible/facts.d/{{ item }}.fact"
    owner: root
    group: root
    mode: 0755
  become: true
  loop:
    - docker_containers
