---
- name: Install hddtemp package
  package:
    name: hddtemp
    state: present
  become: true

- name: Copy hddtemp configuration file
  copy:
    src: hddtemp
    dest: /etc/default/hddtemp
    owner: root
    group: root
    mode: 0644
  become: true
  notify: Restart hddtemp service

- name: Start/enable hddtemp service
  service:
    name: hddtemp
    state: started
    enabled: yes
  become: true
