# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
# This will solve the following issue with the iscsid container:
#
# mkdir /sys/kernel/config: operation not permitted
#
# https://bugs.launchpad.net/kolla/+bug/1631072

- name: Add configfs to /etc/modules
  lineinfile:
    dest: /etc/modules
    regexp: ''
    insertafter: EOF
    line: 'configfs'
  become: true

- name: Load configfs
  modprobe:
    name: configfs
    state: present
  become: true

- name: Start/enable sys-kernel-config.mount
  systemd:
    name: sys-kernel-config.mount
    state: started
    enabled: yes
  become: true

# This will solve the following issue with the iscsid container:
#
# iscsid: Can not bind IPC socket
#
# http://docs.oracle.com/cd/E64747_01/E68930/html/osrns-issues-22244208.html

- name: Remove open-iscsi
  package:
    name: open-iscsi
    state: absent
  become: true
