---
- name: common - enable kernel modules
  lineinfile:
    line: "{{ item }}"
    state: present
    dest: /etc/modules
  become: true
  with_items: "{{ kernel_modules_common }}"

- name: common - load bonding kernel module
  modprobe:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ kernel_modules_common }}"
