---
- name: common - include time tasks
  include: time.yml
  tags: time

- name: common - include kernel modules tasks
  include: kernel-modules.yml
  tags: kernel_modules

- name: common - include packages tasks
  include: packages.yml
  tags: packages

- name: common - include logging tasks
  include: logging.yml
  tags: logging

- name: common - include sysctl tasks
  include: sysctl.yml
  with_items: "{{ sysctl_common }}"
  tags: sysctl

- name: common - include services tasks
  include: services.yml
  tags: services

- name: common - include facts tasks
  include: facts.yml
  tags: facts

- name: common - include motd tasks
  include: motd.yml
  tags: motd

- name: common - include cleanup tasks
  include: cleanup.yml
  tags: cleanup
