---
- name: Cleanup /etc/update-motd.d
  file:
    state: absent
    path: "/etc/update-motd.d/{{ item }}"
  become: true
  with_items:
    - 50-landscape-sysinfo
    - 50-motd-news
    - 80-livepatch

- name: Disable motd banner in ssh pam session
  replace:
    path: /etc/pam.d/sshd
    regexp: "{{ item.regex }}"
    replace: "{{ item.replace }}"
  become: true
  with_items:
    - regex: '^session.*optional.*pam_motd.so.*motd=/run/motd.dynamic$'
      replace: '# session  optional  pam_motd.so  motd=/run/motd.dynamic'
    - regex: '^session.*optional.*pam_motd.so.*noupdate$'
      replace: '# session  optional  pam_motd.so  noupdate'
