---
- name: common - cleanup /etc/update-motd.d
  file:
    state: absent
    path: "{{ item }}"
  become: true
  with_items:
    - 00-header
    - 10-help-text
    - 90-updates-available
    - 91-release-upgrade

- name: common - disable motd banner in ssh pam session
  replace:
    path: /etc/pam.d/sshd
    regexp: "{{ item.regex }}"
    replace: "{{ item.replace }}"
  become: true
  with_items:
    - regex: '^session.*optional.*pam_motd.so.*motd=/run/motd.dynamic$'
      replace: '# session  optional  pam_motd.so  motd=/run/motd.dynamic'
    - regex: '^session.*optional.*pam_motd.so.*noupdate$'
      replace: '# session  optional  pam_motd.so  noupdate'
