# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Install ethtool package
  package:
    name: ethtool
    state: present
  become: true

- name: Enable bonding kernel module
  lineinfile:
    line: bonding
    state: present
    dest: /etc/modules
  become: true

- name: Load bonding kernel module
  modprobe:
    name: bonding
    state: present
  become: true

- name: Enable 8021q kernel module
  lineinfile:
    line: 8021q
    state: present
    dest: /etc/modules
  become: true

- name: Load 8021q kernel module
  modprobe:
    name: 8021q
    state: present
  become: true
