---
- name: Copy operator user sudoers file
  template:
    src: operator-sudoers.j2
    dest: "/etc/sudoers.d/{{ bc_operator_user }}-sudoers"
    owner: root
    group: root
    mode: 0440
  become: true

- name: Set ssh authorized keys
  authorized_key:
    key: "{{ item }}"
    user: "{{ bc_operator_user }}"
  with_items: "{{ bc_authorized_keys }}"
  become: true

- name: Set language variables in bashrc configuration file
  lineinfile:
    dest: "/home/{{ bc_operator_user }}/.bashrc"
    line: "{{ item }}"
  with_items:
    - "export LANGUAGE=en_US.UTF-8"
    - "export LANG=en_US.UTF-8"
    - "export LC_ALL=en_US.UTF-8"
  become: true

- name: Set password of operator user
  user:
    name: "{{ bc_operator_user }}"
    update_password: always
    password: "{{ bc_operator_password }}"
  become: True

- name: Set ssh authorized key (kolla)
  authorized_key:
    user: "{{ bc_operator_user }}"
    key: "{{ bc_kolla_public_key }}"
  become: true

- name: Set ssh private key (kolla)
  copy:
    content: "{{ bc_kolla_private_key }}"
    dest: "/home/{{ bc_operator_user }}/.ssh/id_rsa.kolla"
    owner: "{{ bc_operator_user }}"
    mode: 0600
  become: true
  when: "'kolla' in group_names"
