---
- name: Update package cache
  apt:
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time_common }}"
  become: true

- name: Upgrade packages
  apt:
    upgrade: dist
  become: true
  when: upgrade_packages_common|bool

- name: Cleanup installed packages
  apt:
    name: "{{ cleanup_packages_common }}"
    state: absent
    purge: yes
  become: true

- name: Install required packages
  apt:
    name: "{{ required_packages_common }}"
    state: present
  become: true

- name: Install microcode packages
  apt:
    name: "{{ microcode_packages_common }}"
    state: present
  become: true
  when:
    - install_microcode_package_common|bool

- name: Uninstall unattended-upgrades package
  apt:
    name: unattended-upgrades
    state: absent
    purge: yes
  become: true

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  become: true

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  become: true
