---
- name: common - update package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: common - upgrade packages
  apt:
    upgrade: dist
  become: true

- name: common - cleanup installed packages
  package:
    name: "{{ item }}"
    state: absent
  become: true
  with_items: "{{ cleanup_packages_common }}"

- name: common - install required packages
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ required_packages_common }}"

- name: common - remove useless packages from the cache
  apt:
    autoclean: yes
  become: true

- name: common - remove dependencies that are no longer required
  apt:
    autoremove: yes
  become: true
