---
- name: Update package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Upgrade packages
  apt:
    upgrade: dist
  become: true

- name: Cleanup installed packages
  package:
    name: "{{ item }}"
    state: absent
  become: true
  with_items: "{{ cleanup_packages_common }}"

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ required_packages_common }}"

- name: Install packages required by cockpit
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ required_packages_cockpit }}"

- name: Install intel-microcode package
  package:
    name: intel-microcode
    state: present
  become: true
  when:
    - install_microcode_package_common|bool
    - "'amd' not in ansible_processor"

- name: Install amd64-microcode package
  package:
    name: amd64-microcode
    state: present
  become: true
  when:
    - install_microcode_package_common|bool
    - "'amd' in ansible_processor"

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  become: true

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  become: true
