---
- name: Update package cache
  apt:
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time_common }}"
  become: true

- name: Upgrade packages
  apt:
    upgrade: dist
  become: true
  when: upgrade_packages_common|bool

- name: Cleanup installed packages
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  become: true
  with_items: "{{ cleanup_packages_common }}"

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ required_packages_common }}"

- name: Install microcode packages
  apt:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - amd64-microcode
    - intel-microcode
  when:
    - install_microcode_package_common|bool

- name: Disable unattended-upgrades service
  service:
    name: unattended-upgrades.service
    state: stopped
    enabled: no
  become: true

- name: Uninstall unattended-upgrades package
  apt:
    name: unattended-upgrades
    state: absent
    purge: yes
  become: true

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  become: true

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  become: true
