---
- name: Cleanup installed packages
  package:
    name: "{{ item }}"
    state: absent
  become: true
  with_items: "{{ cleanup_packages_common }}"

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ required_packages_common }}"
