# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
# FIXME: set repositories for CentOS

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
  tags:
    - skip_ansible_lint
  become: true
