# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
# NOTE: http://docs.openstack.org/developer/kolla-ansible/security.html#selinux
- name: Disable selinux
  selinux:
    state: disabled
  become: true

# FIXME: set repositories for CentOS

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
  tags:
    - skip_ansible_lint
  become: true
