# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Ensure resolvconf is installed
  package:
    name: resolvconf
    state: present
  become: true

- name: Copy head file
  template:
    src: head.j2
    dest: /etc/resolvconf/resolv.conf.d/head
    owner: root
    group: root
    mode: 0644
  become: true

- name: Start/Enable resolvconf service
  service:
    name: resolvconf
    state: started
    enabled: yes
  ignore_errors: true
  become: true

- name: Update resolvconf file
  command: resolvconf -u
  become: true
