---
- name: Collect facts about services
  scan_services:

- name: Start/enable required services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  become: true
  ignore_errors: yes
  with_items: "{{ required_services_common }}"
  when: item + ".service" in services

- name: Cleanup services
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  become: true
  ignore_errors: yes
  with_items: "{{ cleanup_services_common }}"
  when: item + ".service" in services
