---
- name: common - collect facts about services
  scan_services:
  register: services_state

- name: common - cleanup services
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  become: true
  ignore_errors: yes
  with_items: "{{ cleanup_services_common }}"
  when: "'{{ item }}.service' in services_state"
