---
- name: common - collect facts about services
  scan_services:
  register: services_state

- name: common - start/enable required services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  become: true
  ignore_errors: yes
  with_items: "{{ required_services_common }}"
  when: "'{{ item }}' in services_state"

- name: common - cleanup services
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  become: true
  ignore_errors: yes
  with_items: "{{ cleanup_services_common }}"
  when: "'{{ item }}' in services_state"
