---
- name: "Set sysctl parameters on {{ item }} nodes"
  sysctl:
    name: "{{ item_in_block.name }}"
    value: "{{ item_in_block.value }}"
    sysctl_set: yes
    sysctl_file: "/etc/sysctl.d/{{ item }}.conf"
  when: "item in group_names or item == 'all'"
  with_items: "{{ sysctl_common[item] }}"
  become: true
  loop_control:
    loop_var: item_in_block
