# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
# https://github.com/docker-library/elasticsearch/issues/98
- name: set vm.max_map_count on elasticsearch nodes
  sysctl:
    name: vm.max_map_count
    value: 262144
    sysctl_set: yes
    sysctl_file: /etc/sysctl.d/elasticsearch.conf
  when: "'elasticsearch' in group_names"
  become: true

# RabbitMQ tuning parameters

# net.ipv4.tcp_keepalive_time: 6
# net.ipv4.tcp_keepalive_intvl: 3
# net.ipv4.tcp_keepalive_probes: 3
# net.core.wmem_max: 16777216
# net.core.rmem_max: 16777216
# net.ipv4.tcp_fin_timeout: 20
# net.ipv4.tcp_tw_reuse: 1
# net.core.somaxconn: 4096
# net.ipv4.tcp_syncookies: 0
# net.ipv4.tcp_max_syn_backlog: 8192
