---
- name: Restart rsyslog service
  service:
    name: rsyslog
    state: restarted
  become: true

- name: Restart hddtemp service
  service:
    name: hddtemp
    state: restarted
  become: true

- name: Restart smartd service
  service:
    name: smartd
    state: restarted
  become: true
