---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: False
    login_cmd_template: 'docker exec -ti {instance} bash'
    ansible_connection_options:
      ansible_connection: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yamllint.yml
# NOTE: Start the required container with the following command
# docker run -d --name osism-systemd --hostname osism-systemd \
#   --security-opt seccomp=unconfined --tmpfs /run --tmpfs /run/lock \
#   -v /sys/fs/cgroup:/sys/fs/cgroup:ro -t solita/ubuntu-systemd:16.04
platforms:
  - name: osism-systemd
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - lint
    - side_effect
    - verify
    - destroy
